Test
JuanOssa1/TheAmazingStore pull request #1
Opened 2023-02-07 20:25 UTC by JuanOssa1

2023-02-07 20:28 UTC, JuanGMejia requested changes

2023-02-07 20:28 UTC, JuanGMejia commented on Styles/main.scss
> +    grid-row: 3; //alto//aaaa
este comentario no

2023-02-07 20:31 UTC, JuanGMejia approved these changes

2023-02-08 17:06 UTC, JuanGMejia commented on Js/main.js
> +        //loadData(url+"?q="+userInput.value)
remove commented lines

2023-02-08 17:06 UTC, JuanGMejia commented on Js/main.js
>      console.log(ul)
remove console logs

2023-02-08 17:07 UTC, JuanGMejia commented on Js/main.js
> +    console.log(resul)
remove console log

2023-02-08 17:21 UTC, JuanOssa1 commented
Ya removi los console logs, en los scss hay unos comments pero los tengo ahi porque son cosas que te quiero preguntar cuando nos reunamos

2023-02-08 19:14 UTC, JuanGMejia approved these changes

2023-02-08 19:16 UTC, JuanGMejia approved these changes

2023-02-08 19:29 UTC, merged